from _typeshed import Incomplete

TIME_SERIES_RESULT_FORMAT: str
TABLE_RESULT_FORMAT: str
ADX_TIME_SERIES_RESULT_FORMAT: str

class AzureDataExplorerTarget:
    database: Incomplete
    query: Incomplete
    resultFormat: Incomplete
    alias: Incomplete
    refId: Incomplete
    def to_json_data(self): ...
    def __init__(self, database, query, resultFormat, alias, refId) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...
