from _typeshed import Incomplete

class AzureMonitorMetricsTarget:
    aggregation: Incomplete
    dimensionFilters: Incomplete
    metricDefinition: Incomplete
    metricName: Incomplete
    metricNamespace: Incomplete
    resourceGroup: Incomplete
    resourceName: Incomplete
    timeGrain: Incomplete
    queryType: Incomplete
    subscription: Incomplete
    refId: Incomplete
    alias: Incomplete
    def to_json_data(self): ...
    def __init__(self, aggregation, dimensionFilters, metricDefinition, metricName, metricNamespace, resourceGroup, resourceName, timeGrain, queryType, subscription, refId, alias) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class AzureLogsTarget:
    query: Incomplete
    resource: Incomplete
    resultFormat: Incomplete
    queryType: Incomplete
    subscription: Incomplete
    refId: Incomplete
    def to_json_data(self): ...
    def __init__(self, query, resource, resultFormat, queryType, subscription, refId) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class AzureResourceGraphTarget:
    query: Incomplete
    resource: Incomplete
    queryType: Incomplete
    subscription: Incomplete
    refId: Incomplete
    def to_json_data(self): ...
    def __init__(self, query, resource, queryType, subscription, refId) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...
