
from typing import Any

class Panel:
    """Base class for Grafana panels."""

    def __init__(
        self,
        dataSource: Any = ...,
        targets: Any = ...,
        title: Any = ...,
        cacheTimeout: Any = ...,
        description: Any = ...,
        editable: Any = ...,
        error: Any = ...,
        height: Any = ...,
        gridPos: Any = ...,
        hideTimeOverride: Any = ...,
        id: Any = ...,
        interval: Any = ...,
        links: Any = ...,
        maxDataPoints: Any = ...,
        minSpan: Any = ...,
        repeat: Any = ...,
        span: Any = ...,
        thresholds: Any = ...,
        thresholdType: Any = ...,
        timeFrom: Any = ...,
        timeShift: Any = ...,
        transparent: Any = ...,
        transformations: Any = ...,
        extraJson: Any = ...,
    ) -> None: ...
    def panel_json(self) -> dict[str, Any]: ...
    def to_json_data(self) -> dict[str, Any]: ...


class Dashboard:
    def __init__(
        self,
        title: Any,
        annotations: Any = ...,
        description: Any = ...,
        editable: Any = ...,
        gnetId: Any = ...,
        graphTooltip: Any = ...,
        hideControls: Any = ...,
        id: Any = ...,
        inputs: Any = ...,
        links: Any = ...,
        panels: Any = ...,
        refresh: Any = ...,
        rows: Any = ...,
        schemaVersion: Any = ...,
        sharedCrosshair: Any = ...,
        style: Any = ...,
        tags: Any = ...,
        templating: Any = ...,
        time: Any = ...,
        timePicker: Any = ...,
        timezone: Any = ...,
        version: Any = ...,
        uid: Any = ...,
    ) -> None: ...
    def to_json_data(self) -> dict[str, Any]: ...
    def auto_panel_ids(self) -> Dashboard: ...

class Time:
    def __init__(self, start: Any, end: Any) -> None: ...
    def to_json_data(self) -> dict[str, Any]: ...

class BarChart:
    def __init__(
        self,
        dataSource: Any = ...,
        targets: Any = ...,
        title: Any = ...,
        cacheTimeout: Any = ...,
        description: Any = ...,
        editable: Any = ...,
        error: Any = ...,
        height: Any = ...,
        gridPos: Any = ...,
        hideTimeOverride: Any = ...,
        id: Any = ...,
        interval: Any = ...,
        links: Any = ...,
        maxDataPoints: Any = ...,
        minSpan: Any = ...,
        repeat: Any = ...,
        span: Any = ...,
        thresholds: Any = ...,
        thresholdType: Any = ...,
        timeFrom: Any = ...,
        timeShift: Any = ...,
        transparent: Any = ...,
        transformations: Any = ...,
        extraJson: Any = ...,
        orientation: Any = ...,
        xTickLabelRotation: Any = ...,
        xTickLabelSpacing: Any = ...,
        showValue: Any = ...,
        stacking: Any = ...,
        groupWidth: Any = ...,
        barWidth: Any = ...,
        barRadius: Any = ...,
        tooltipMode: Any = ...,
        tooltipSort: Any = ...,
        showLegend: Any = ...,
        legendDisplayMode: Any = ...,
        legendPlacement: Any = ...,
        legendCalcs: Any = ...,
        lineWidth: Any = ...,
        fillOpacity: Any = ...,
        gradientMode: Any = ...,
        axisPlacement: Any = ...,
        axisLabel: Any = ...,
        axisColorMode: Any = ...,
        scaleDistributionType: Any = ...,
        axisCenteredZero: Any = ...,
        hideFromTooltip: Any = ...,
        hideFromViz: Any = ...,
        hideFromLegend: Any = ...,
        colorMode: Any = ...,
        fixedColor: Any = ...,
        mappings: Any = ...,
        thresholdsMode: Any = ...,
        thresholdSteps: Any = ...,
        overrides: Any = ...,
    ) -> None: ...
    def to_json_data(self) -> dict[str, Any]: ...

class GridPos:
    def __init__(self, h: Any, w: Any, x: Any, y: Any) -> None: ...
    def to_json_data(self) -> dict[str, Any]: ...

class PieChartv2:
    def __init__(
        self,
        dataSource: Any = ...,
        targets: Any = ...,
        title: Any = ...,
        cacheTimeout: Any = ...,
        description: Any = ...,
        editable: Any = ...,
        error: Any = ...,
        height: Any = ...,
        gridPos: Any = ...,
        hideTimeOverride: Any = ...,
        id: Any = ...,
        interval: Any = ...,
        links: Any = ...,
        maxDataPoints: Any = ...,
        minSpan: Any = ...,
        repeat: Any = ...,
        span: Any = ...,
        thresholds: Any = ...,
        thresholdType: Any = ...,
        timeFrom: Any = ...,
        timeShift: Any = ...,
        transparent: Any = ...,
        transformations: Any = ...,
        extraJson: Any = ...,
        custom: Any = ...,
        colorMode: Any = ...,
        legendDisplayMode: Any = ...,
        legendPlacement: Any = ...,
        legendValues: Any = ...,
        mappings: Any = ...,
        overrides: Any = ...,
        pieType: Any = ...,
        reduceOptionsCalcs: Any = ...,
        reduceOptionsFields: Any = ...,
        reduceOptionsValues: Any = ...,
        tooltipMode: Any = ...,
        unit: Any = ...,
    ) -> None: ...
    def to_json_data(self) -> dict[str, Any]: ...

class RowPanel:
    def __init__(
        self,
        dataSource: Any = ...,
        targets: Any = ...,
        title: Any = ...,
        cacheTimeout: Any = ...,
        description: Any = ...,
        editable: Any = ...,
        error: Any = ...,
        height: Any = ...,
        gridPos: Any = ...,
        hideTimeOverride: Any = ...,
        id: Any = ...,
        interval: Any = ...,
        links: Any = ...,
        maxDataPoints: Any = ...,
        minSpan: Any = ...,
        repeat: Any = ...,
        span: Any = ...,
        thresholds: Any = ...,
        thresholdType: Any = ...,
        timeFrom: Any = ...,
        timeShift: Any = ...,
        transparent: Any = ...,
        transformations: Any = ...,
        extraJson: Any = ...,
        panels: Any = ...,
        collapsed: Any = ...,
    ) -> None: ...
    def to_json_data(self) -> dict[str, Any]: ...

class Stat:
    def __init__(
        self,
        dataSource: Any = ...,
        targets: Any = ...,
        title: Any = ...,
        cacheTimeout: Any = ...,
        description: Any = ...,
        editable: Any = ...,
        error: Any = ...,
        height: Any = ...,
        gridPos: Any = ...,
        hideTimeOverride: Any = ...,
        id: Any = ...,
        interval: Any = ...,
        links: Any = ...,
        maxDataPoints: Any = ...,
        minSpan: Any = ...,
        repeat: Any = ...,
        span: Any = ...,
        thresholdType: Any = ...,
        timeFrom: Any = ...,
        timeShift: Any = ...,
        transparent: Any = ...,
        transformations: Any = ...,
        extraJson: Any = ...,
        alignment: Any = ...,
        color: Any = ...,
        colorMode: Any = ...,
        decimals: Any = ...,
        format: Any = ...,
        graphMode: Any = ...,
        mappings: Any = ...,
        noValue: Any = ...,
        orientation: Any = ...,
        overrides: Any = ...,
        reduceCalc: Any = ...,
        fields: Any = ...,
        textMode: Any = ...,
        thresholds: Any = ...,
    ) -> None: ...
    def to_json_data(self) -> dict[str, Any]: ...

class Table:
    def __init__(
        self,
        dataSource: Any = ...,
        targets: Any = ...,
        title: Any = ...,
        cacheTimeout: Any = ...,
        description: Any = ...,
        editable: Any = ...,
        error: Any = ...,
        height: Any = ...,
        gridPos: Any = ...,
        hideTimeOverride: Any = ...,
        id: Any = ...,
        interval: Any = ...,
        links: Any = ...,
        maxDataPoints: Any = ...,
        minSpan: Any = ...,
        repeat: Any = ...,
        span: Any = ...,
        thresholds: Any = ...,
        thresholdType: Any = ...,
        timeFrom: Any = ...,
        timeShift: Any = ...,
        transparent: Any = ...,
        transformations: Any = ...,
        extraJson: Any = ...,
        align: Any = ...,
        colorMode: Any = ...,
        columns: Any = ...,
        displayMode: Any = ...,
        fontSize: Any = ...,
        filterable: Any = ...,
        mappings: Any = ...,
        overrides: Any = ...,
        showHeader: Any = ...,
        unit: Any = ...,
        sortBy: Any = ...,
    ) -> None: ...
    def to_json_data(self) -> dict[str, Any]: ...

class TimeSeries:
    def __init__(
        self,
        dataSource: Any = ...,
        targets: Any = ...,
        title: Any = ...,
        cacheTimeout: Any = ...,
        description: Any = ...,
        editable: Any = ...,
        error: Any = ...,
        height: Any = ...,
        gridPos: Any = ...,
        hideTimeOverride: Any = ...,
        id: Any = ...,
        interval: Any = ...,
        links: Any = ...,
        maxDataPoints: Any = ...,
        minSpan: Any = ...,
        repeat: Any = ...,
        span: Any = ...,
        thresholds: Any = ...,
        thresholdType: Any = ...,
        timeFrom: Any = ...,
        timeShift: Any = ...,
        transparent: Any = ...,
        transformations: Any = ...,
        extraJson: Any = ...,
        axisPlacement: Any = ...,
        axisLabel: Any = ...,
        barAlignment: Any = ...,
        colorMode: Any = ...,
        drawStyle: Any = ...,
        fillOpacity: Any = ...,
        gradientMode: Any = ...,
        legendDisplayMode: Any = ...,
        legendPlacement: Any = ...,
        legendCalcs: Any = ...,
        lineInterpolation: Any = ...,
        lineWidth: Any = ...,
        mappings: Any = ...,
        overrides: Any = ...,
        pointSize: Any = ...,
        scaleDistributionType: Any = ...,
        scaleDistributionLog: Any = ...,
        spanNulls: Any = ...,
        showPoints: Any = ...,
        stacking: Any = ...,
        tooltipMode: Any = ...,
        tooltipSort: Any = ...,
        unit: Any = ...,
        thresholdsStyleMode: Any = ...,
        valueMin: Any = ...,
        valueMax: Any = ...,
        valueDecimals: Any = ...,
        axisSoftMin: Any = ...,
        axisSoftMax: Any = ...,
    ) -> None: ...
    def to_json_data(self) -> dict[str, Any]: ...
