from _typeshed import Incomplete
from grafanalib.core import AlertCondition as AlertCondition

DATE_HISTOGRAM_DEFAULT_FIELD: str
ORDER_ASC: str
ORDER_DESC: str

class CountMetricAgg:
    id: Incomplete
    hide: Incomplete
    inline: Incomplete
    settings: Incomplete
    def to_json_data(self): ...
    def __init__(self, id, hide, inline) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class MaxMetricAgg:
    field: Incomplete
    id: Incomplete
    hide: Incomplete
    inline: Incomplete
    settings: Incomplete
    def to_json_data(self): ...
    def __init__(self, field, id, hide, inline) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class CardinalityMetricAgg:
    field: Incomplete
    id: Incomplete
    hide: Incomplete
    inline: Incomplete
    settings: Incomplete
    def to_json_data(self): ...
    def __init__(self, field, id, hide, inline) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class AverageMetricAgg:
    field: Incomplete
    id: Incomplete
    hide: Incomplete
    inline: Incomplete
    settings: Incomplete
    def to_json_data(self): ...
    def __init__(self, field, id, hide, inline) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class DerivativeMetricAgg:
    field: Incomplete
    hide: Incomplete
    id: Incomplete
    pipelineAgg: Incomplete
    unit: Incomplete
    def to_json_data(self): ...
    def __init__(self, field, hide, id, pipelineAgg, unit) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class SumMetricAgg:
    field: Incomplete
    id: Incomplete
    hide: Incomplete
    inline: Incomplete
    settings: Incomplete
    def to_json_data(self): ...
    def __init__(self, field, id, hide, inline) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class DateHistogramGroupBy:
    id: Incomplete
    field: Incomplete
    interval: Incomplete
    minDocCount: Incomplete
    def to_json_data(self): ...
    def __init__(self, id, field, interval, minDocCount) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class BucketScriptAgg:
    fields: Incomplete
    id: Incomplete
    hide: Incomplete
    script: Incomplete
    def to_json_data(self): ...
    def __init__(self, fields, id, hide, script) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class Filter:
    label: Incomplete
    query: Incomplete
    def to_json_data(self): ...
    def __init__(self, label, query) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class FiltersGroupBy:
    id: Incomplete
    filters: Incomplete
    def to_json_data(self): ...
    def __init__(self, id, filters) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class TermsGroupBy:
    field: Incomplete
    id: Incomplete
    minDocCount: Incomplete
    order: Incomplete
    orderBy: Incomplete
    size: Incomplete
    def to_json_data(self): ...
    def __init__(self, field, id, minDocCount, order, orderBy, size) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class ElasticsearchTarget:
    alias: Incomplete
    bucketAggs: Incomplete
    metricAggs: Incomplete
    query: Incomplete
    refId: Incomplete
    timeField: Incomplete
    hide: Incomplete
    def auto_bucket_agg_ids(self): ...
    def to_json_data(self): ...
    def __init__(self, alias, bucketAggs, metricAggs, query, refId, timeField, hide) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class ElasticsearchAlertCondition(AlertCondition):
    target: Incomplete
    def __init__(self, evaluator, timeRange, operator, reducerType, useNewAlerts, type, target) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class MinMetricAgg:
    field: Incomplete
    id: Incomplete
    hide: Incomplete
    inline: Incomplete
    settings: Incomplete
    def to_json_data(self): ...
    def __init__(self, field, id, hide, inline) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class PercentilesMetricAgg:
    field: Incomplete
    id: Incomplete
    hide: Incomplete
    inline: Incomplete
    percents: Incomplete
    settings: Incomplete
    def to_json_data(self): ...
    def __init__(self, field, id, hide, inline, percents, settings) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class RateMetricAgg:
    field: Incomplete
    id: Incomplete
    hide: Incomplete
    unit: Incomplete
    mode: Incomplete
    script: Incomplete
    settings: Incomplete
    def to_json_data(self): ...
    def __init__(self, field, id, hide, unit, mode, script) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...
