from _typeshed import Incomplete

class HumioTarget:
    humioQuery: Incomplete
    humioRepository: Incomplete
    refId: Incomplete
    def to_json_data(self): ...
    def __init__(self, humioQuery, humioRepository, refId) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...
