from _typeshed import Incomplete

TIME_SERIES_TARGET_FORMAT: str

class InfluxDBTarget:
    alias: Incomplete
    format: Incomplete
    datasource: Incomplete
    measurement: Incomplete
    query: Incomplete
    rawQuery: Incomplete
    refId: Incomplete
    def to_json_data(self): ...
    def __init__(self, alias, format, datasource, measurement, query, rawQuery, refId) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...
