from _typeshed import Incomplete

class _IsInValidator:
    choices: Incomplete
    def __call__(self, inst, attr, value) -> None: ...
    def __init__(self, choices) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

def is_in(choices): ...
def is_interval(instance, attribute, value) -> None: ...
def is_color_code(instance, attribute, value) -> None: ...

class _ListOfValidator:
    etype: Incomplete
    def __call__(self, inst, attr, value): ...
    def __init__(self, etype) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

def is_list_of(etype): ...
