from _typeshed import Incomplete
from grafanalib.core import (
    BLANK as BLANK,
    DEFAULT_ROW_HEIGHT as DEFAULT_ROW_HEIGHT,
    GREEN as GREEN,
    RGBA as RGBA,
    DashboardLink as DashboardLink,
    Percent as Percent,
    Pixels as Pixels,
)
from grafanalib.validators import (
    is_color_code as is_color_code,
    is_in as is_in,
    is_interval as is_interval,
    is_list_of as is_list_of,
)

ZABBIX_TRIGGERS_TYPE: str
ZABBIX_QMODE_METRICS: int
ZABBIX_QMODE_SERVICES: int
ZABBIX_QMODE_TEXT: int
ZABBIX_SLA_PROP_STATUS: Incomplete
ZABBIX_SLA_PROP_SLA: Incomplete
ZABBIX_SLA_PROP_OKTIME: Incomplete
ZABBIX_SLA_PROP_PROBTIME: Incomplete
ZABBIX_SLA_PROP_DOWNTIME: Incomplete
ZABBIX_EVENT_PROBLEMS: Incomplete
ZABBIX_EVENT_OK: Incomplete
ZABBIX_EVENT_ALL: Incomplete
ZABBIX_TRIGGERS_SHOW_ALL: str
ZABBIX_TRIGGERS_SHOW_ACK: str
ZABBIX_TRIGGERS_SHOW_NACK: str
ZABBIX_SORT_TRIGGERS_BY_CHANGE: Incomplete
ZABBIX_SORT_TRIGGERS_BY_SEVERITY: Incomplete
ZABBIX_SEVERITY_COLORS: Incomplete

def convertZabbixSeverityColors(colors): ...

class ZabbixTargetOptions:
    showDisabledItems: Incomplete
    def to_json_data(self): ...
    def __init__(self, showDisabledItems) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class ZabbixTargetField:
    filter: Incomplete
    def to_json_data(self): ...
    def __init__(self, filter) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class ZabbixTarget:
    application: Incomplete
    expr: Incomplete
    functions: Incomplete
    group: Incomplete
    host: Incomplete
    intervalFactor: Incomplete
    item: Incomplete
    itService: Incomplete
    mode: Incomplete
    options: Incomplete
    refId: Incomplete
    slaProperty: Incomplete
    textFilter: Incomplete
    useCaptureGroups: Incomplete
    def to_json_data(self): ...
    def __init__(self, application, expr, functions, group, host, intervalFactor, item, itService, mode, options, refId, slaProperty, textFilter, useCaptureGroups) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class ZabbixDeltaFunction:
    added: Incomplete
    def to_json_data(self): ...
    def __init__(self, added) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class ZabbixGroupByFunction:
    added: Incomplete
    interval: Incomplete
    function: Incomplete
    def to_json_data(self): ...
    def __init__(self, added, interval, function) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class ZabbixScaleFunction:
    added: Incomplete
    factor: Incomplete
    def to_json_data(self): ...
    def __init__(self, added, factor) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class ZabbixAggregateByFunction:
    added: Incomplete
    interval: Incomplete
    function: Incomplete
    def to_json_data(self): ...
    def __init__(self, added, interval, function) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class ZabbixAverageFunction:
    added: Incomplete
    interval: Incomplete
    def to_json_data(self): ...
    def __init__(self, added, interval) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class ZabbixMaxFunction:
    added: Incomplete
    interval: Incomplete
    def to_json_data(self): ...
    def __init__(self, added, interval) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class ZabbixMedianFunction:
    added: Incomplete
    interval: Incomplete
    def to_json_data(self): ...
    def __init__(self, added, interval) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class ZabbixMinFunction:
    added: Incomplete
    interval: Incomplete
    def to_json_data(self): ...
    def __init__(self, added, interval) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class ZabbixSumSeriesFunction:
    added: Incomplete
    def to_json_data(self): ...
    def __init__(self, added) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class ZabbixBottomFunction:
    added: Incomplete
    number: Incomplete
    function: Incomplete
    def to_json_data(self): ...
    def __init__(self, added, number, function) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class ZabbixTopFunction:
    added: Incomplete
    number: Incomplete
    function: Incomplete
    def to_json_data(self): ...
    def __init__(self, added, number, function) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class ZabbixTrendValueFunction:
    added: Incomplete
    type: Incomplete
    def to_json_data(self): ...
    def __init__(self, added, type) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class ZabbixTimeShiftFunction:
    added: Incomplete
    interval: Incomplete
    def to_json_data(self): ...
    def __init__(self, added, interval) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class ZabbixSetAliasFunction:
    alias: Incomplete
    added: Incomplete
    def to_json_data(self): ...
    def __init__(self, alias, added) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class ZabbixSetAliasByRegexFunction:
    regexp: Incomplete
    added: Incomplete
    def to_json_data(self): ...
    def __init__(self, regexp, added) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

def zabbixMetricTarget(application, group, host, item, functions=[]): ...
def zabbixServiceTarget(service, sla=...): ...
def zabbixTextTarget(application, group, host, item, text, useCaptureGroups: bool = False): ...

class ZabbixColor:
    color: Incomplete
    priority: Incomplete
    severity: Incomplete
    show: Incomplete
    def to_json_data(self): ...
    def __init__(self, color, priority, severity, show) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class ZabbixTrigger:
    application: Incomplete
    group: Incomplete
    host: Incomplete
    trigger: Incomplete
    def to_json_data(self): ...
    def __init__(self, application, group, host, trigger) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class ZabbixTriggersPanel:
    dataSource: Incomplete
    title: Incomplete
    ackEventColor: Incomplete
    ageField: Incomplete
    customLastChangeFormat: Incomplete
    description: Incomplete
    fontSize: Incomplete
    height: Incomplete
    hideHostsInMaintenance: Incomplete
    hostField: Incomplete
    hostTechNameField: Incomplete
    id: Incomplete
    infoField: Incomplete
    lastChangeField: Incomplete
    lastChangeFormat: Incomplete
    limit: Incomplete
    links: Incomplete
    markAckEvents: Incomplete
    minSpan: Incomplete
    okEventColor: Incomplete
    pageSize: Incomplete
    repeat: Incomplete
    scroll: Incomplete
    severityField: Incomplete
    showEvents: Incomplete
    showTriggers: Incomplete
    sortTriggersBy: Incomplete
    span: Incomplete
    statusField: Incomplete
    transparent: Incomplete
    triggerSeverity: Incomplete
    triggers: Incomplete
    def to_json_data(self): ...
    def __init__(self, dataSource, title, ackEventColor, ageField, customLastChangeFormat, description, fontSize, height, hideHostsInMaintenance, hostField, hostTechNameField, id, infoField, lastChangeField, lastChangeFormat, limit, links, markAckEvents, minSpan, okEventColor, pageSize, repeat, scroll, severityField, showEvents, showTriggers, sortTriggersBy, span, statusField, transparent, triggers) -> None: ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...
